<?php

namespace App\Exceptions;

use App\Providers\Renderable;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that are not reported.
     *
     * @var array
     */
    protected $dontReport = [
        // \Illuminate\Database\Eloquent\ModelNotFoundException::class,
    ];

    /**
     * Report or log an exception.
     *
     * @param  \Throwable  $exception
     * @return void
     *
     * @throws \Exception
     */
    public function report(Throwable $exception)
    {
        parent::report($exception);
    }



    public function renderForConsole($output, Throwable $e)
    {
        if ($e instanceof Renderable) {
            $e->render($output);
            return;
        }
        parent::renderForConsole($output, $e);
    }

    protected function renderExceptionWithWhoops(Throwable $e)
    {
        return parent::renderExceptionWithWhoops($e); // TODO: Change the autogenerated stub
    }


}
